// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrations/introspection need a direct (non-pooled) connection — DDL
  // over PgBouncer's transaction-mode pooler (what DATABASE_URL now points
  // at, for the app's own runtime queries) is unreliable. DIRECT_URL is the
  // same Supabase database's session-mode connection (port 5432).
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
