// User-manual content, authored in-repo (no DB). Rendered by
// app/(backend)/manual/**. Screenshots live in public/manual/screens/ and
// are (re)generated by scripts/capture-manual-screens.mjs — each `shot`
// block's `src` must match a file that script produces.
//
// Keep this file free of Prisma / server imports: the manual nav rail is a
// client component and imports MANUAL_TOPICS. Role -> audience mapping
// lives in app/lib/manual-access.ts instead.

export const MANUAL_AUDIENCES = ["user", "approver", "admin"] as const;
export type ManualAudience = (typeof MANUAL_AUDIENCES)[number];

export const AUDIENCE_LABEL: Record<ManualAudience, string> = {
  user: "For Requesters",
  approver: "For Approvers",
  admin: "For Administrators",
};

export const AUDIENCE_BLURB: Record<ManualAudience, string> = {
  user: "Everyone who raises and follows up on support tickets.",
  approver: "Department approvers who review tickets that need sign-off.",
  admin: "Administrators who triage tickets and manage master data.",
};

export type ManualBlock =
  | { type: "p"; text: string }
  | { type: "steps"; items: string[] }
  | { type: "bullets"; items: string[] }
  | { type: "note"; variant: "tip" | "info" | "warning"; text: string }
  | { type: "shot"; src: string; caption: string };

export type ManualSection = {
  heading: string;
  blocks: ManualBlock[];
};

export type ManualTopic = {
  slug: string;
  audience: ManualAudience;
  icon: string; // Bootstrap Icons class
  title: string;
  summary: string;
  sections: ManualSection[];
};

const SHOT = (name: string, caption: string): ManualBlock => ({
  type: "shot",
  src: `/manual/screens/${name}.png`,
  caption,
});

export const MANUAL_TOPICS: ManualTopic[] = [
  // ----------------------------------------------------------------- user
  {
    slug: "getting-started",
    audience: "user",
    icon: "bi-box-arrow-in-right",
    title: "Signing in & finding your way around",
    summary: "Sign in with email/password or your Microsoft account, and learn the layout.",
    sections: [
      {
        heading: "Signing in",
        blocks: [
          { type: "p", text: "Open the app and you will land on the sign-in page. Use whichever method your organisation set up for you." },
          {
            type: "steps",
            items: [
              "Enter your work email and password, then choose Sign In.",
              "Or choose Sign in with Microsoft and complete the Microsoft prompt.",
              "If you forget your password, use Forgot password on the sign-in page.",
            ],
          },
          SHOT("login", "The sign-in page."),
          { type: "note", variant: "info", text: "If your account has been deactivated or suspended, sign-in is refused even with the right password. Contact an administrator." },
        ],
      },
      {
        heading: "The screen layout",
        blocks: [
          { type: "p", text: "After signing in you see a left sidebar for navigation, a top bar with search and the notification bell, and the current page in the middle." },
          { type: "bullets", items: [
            "Ticket — the tickets you have raised.",
            "Assigned Ticket — tickets assigned to you (individually or through a group).",
            "Lesson Learned — a searchable knowledge base of past solutions.",
            "User Manual — this guide.",
          ] },
          SHOT("user-tickets", "The sidebar and a typical list page."),
        ],
      },
    ],
  },
  {
    slug: "create-ticket",
    audience: "user",
    icon: "bi-plus-square",
    title: "Raising a support ticket",
    summary: "Fill in the New Ticket form; some categories also need an approver's sign-off.",
    sections: [
      {
        heading: "Filling in the form",
        blocks: [
          { type: "steps", items: [
            "From Ticket, choose New Ticket.",
            "Enter a Title and Description that explain the problem.",
            "Enter a Telephone number we can reach you on.",
            "Pick the Category that best matches your issue.",
            "Choose Submit.",
          ] },
          SHOT("user-new-ticket", "The New Ticket form."),
          { type: "note", variant: "info", text: "Company and Department are taken from your profile. If they are not set, an administrator has to add them before you can raise a ticket." },
        ],
      },
      {
        heading: "Categories that need approval",
        blocks: [
          { type: "p", text: "Some categories require a department approver to sign off before work begins." },
          { type: "steps", items: [
            "When you pick such a category, a Message to approver box appears.",
            "Explain why the request is needed, then Submit.",
            "The ticket is created and an approval request is sent to your department's approver(s).",
            "You are notified when it is approved or rejected.",
          ] },
        ],
      },
      {
        heading: "Attachments",
        blocks: [
          { type: "p", text: "Add screenshots or files while creating the ticket, or later from the ticket page. They appear in the ticket's Attachments area." },
        ],
      },
    ],
  },
  {
    slug: "track-tickets",
    audience: "user",
    icon: "bi-list-check",
    title: "Tracking your tickets",
    summary: "Search, filter and sort the list of tickets you have raised.",
    sections: [
      {
        heading: "The ticket list",
        blocks: [
          { type: "p", text: "Ticket shows every ticket you have raised, newest first. The badge on the sidebar item counts your tickets that are not yet closed." },
          { type: "bullets", items: [
            "Search by title or ticket number.",
            "Filter by status.",
            "Click a column header to sort; change rows per page at the bottom.",
          ] },
          SHOT("user-tickets", "Your ticket list with search and status filter."),
        ],
      },
      {
        heading: "Ticket statuses",
        blocks: [
          { type: "bullets", items: [
            "NEW — submitted, not yet picked up.",
            "ASSIGNED — someone is working on it.",
            "WAITING — waiting for an approver's decision.",
            "RESOLVED — a fix has been applied; review it and close the ticket.",
            "REOPENED — you reopened it because the problem returned.",
            "CLOSED — finished.",
          ] },
        ],
      },
    ],
  },
  {
    slug: "work-a-ticket",
    audience: "user",
    icon: "bi-chat-left-text",
    title: "Following up: comments, resolution & rating",
    summary: "Add comments, respond when a ticket is resolved, and rate the service.",
    sections: [
      {
        heading: "Comments",
        blocks: [
          { type: "p", text: "Open a ticket to see its full history and comment thread. Add a comment to give more detail or answer a question from the support team. You can attach files to a comment." },
          SHOT("user-ticket-detail", "A ticket page with its history and comment box."),
        ],
      },
      {
        heading: "When a ticket is resolved",
        blocks: [
          { type: "steps", items: [
            "You are notified when the ticket is marked RESOLVED.",
            "Open the ticket and check the fix works for you.",
            "If it does, choose Close Ticket and give a satisfaction rating.",
            "If it does not, add a comment explaining what is still wrong to reopen it.",
          ] },
          { type: "note", variant: "tip", text: "A resolved ticket that no one closes is closed automatically after a while." },
        ],
      },
    ],
  },
  {
    slug: "notifications",
    audience: "user",
    icon: "bi-bell",
    title: "Notifications",
    summary: "The bell in the top bar tells you when something on your tickets changes.",
    sections: [
      {
        heading: "Using the bell",
        blocks: [
          { type: "bullets", items: [
            "A number on the bell is the count of things you have not looked at yet.",
            "Open the bell to see the list; this clears the count.",
            "Choose an item to jump straight to that ticket or approval.",
          ] },
          SHOT("user-notifications", "The notifications list."),
        ],
      },
    ],
  },
  {
    slug: "profile",
    audience: "user",
    icon: "bi-person-gear",
    title: "Your profile, password & API tokens",
    summary: "Update your details, change your password, and create tokens for tools.",
    sections: [
      {
        heading: "Profile & password",
        blocks: [
          { type: "steps", items: [
            "Open Profile from the top-right user menu.",
            "Edit your name or telephone and save.",
            "To change your password, enter your current password and a new one of at least 8 characters.",
          ] },
          SHOT("user-profile", "The profile page."),
          { type: "note", variant: "info", text: "Company and Department are shown read-only. Ask an administrator to change them." },
        ],
      },
      {
        heading: "API tokens",
        blocks: [
          { type: "p", text: "A personal access token lets an external tool (for example the MCP integration) act as you." },
          { type: "steps", items: [
            "In the API Tokens card, choose New token and give it a name.",
            "Copy the token now — it is shown only once.",
            "Delete a token any time to revoke it immediately.",
          ] },
          { type: "note", variant: "warning", text: "Treat a token like a password. Only its fingerprint is stored, so a lost token cannot be shown again — delete it and make a new one." },
        ],
      },
    ],
  },
  {
    slug: "search-and-kb",
    audience: "user",
    icon: "bi-search",
    title: "Search & Lesson Learned",
    summary: "Find your tickets fast, and check the knowledge base before raising a ticket.",
    sections: [
      {
        heading: "Global search",
        blocks: [
          { type: "p", text: "The search box in the top bar looks across tickets you are allowed to see. Type part of a title or ticket number." },
        ],
      },
      {
        heading: "Lesson Learned",
        blocks: [
          { type: "p", text: "Lesson Learned collects fixes for recurring problems. Search it first — your issue may already have a documented solution." },
          SHOT("user-lesson-learned", "The Lesson Learned knowledge base."),
        ],
      },
    ],
  },

  // ------------------------------------------------------------- approver
  {
    slug: "approval-queue",
    audience: "approver",
    icon: "bi-clipboard-check",
    title: "The approval queue",
    summary: "Where requests that need your sign-off wait for a decision.",
    sections: [
      {
        heading: "Finding requests",
        blocks: [
          { type: "p", text: "Approval Ticket in the sidebar lists every pending request for the departments where you are an approver. The badge counts them." },
          SHOT("approver-approval-queue", "The approval queue."),
          { type: "note", variant: "info", text: "You only see requests for your own department(s). Requests for other departments go to their approvers." },
        ],
      },
    ],
  },
  {
    slug: "decide-request",
    audience: "approver",
    icon: "bi-check2-square",
    title: "Approving or rejecting",
    summary: "Open a request, read the requester's message, and record your decision.",
    sections: [
      {
        heading: "Making a decision",
        blocks: [
          { type: "steps", items: [
            "Open a request from the approval queue.",
            "Read the ticket details and the requester's message to the approver.",
            "Choose Approve or Reject and add a comment explaining your decision.",
            "Submit. The requester is notified and the ticket moves on (or stops, if rejected).",
          ] },
          SHOT("approver-decide", "Open a request from the approval queue to record your decision."),
        ],
      },
      {
        heading: "More than one approver",
        blocks: [
          { type: "p", text: "A department can have several approvers. The same request appears for all of them, and whoever acts first decides it." },
          { type: "note", variant: "warning", text: "If another approver has already decided, you cannot override it — you will see the request is no longer pending." },
        ],
      },
    ],
  },
  {
    slug: "approver-assigned",
    audience: "approver",
    icon: "bi-person-check",
    title: "Tickets assigned to you",
    summary: "Approvers can also be assigned tickets to work on, individually or via a group.",
    sections: [
      {
        heading: "Your assigned queue",
        blocks: [
          { type: "p", text: "Assigned Ticket lists tickets assigned directly to you or to any group you belong to. It is ordered so the tickets that need action now come first." },
          { type: "bullets", items: [
            "ASSIGNED / REOPENED / NEW appear first — these need you.",
            "RESOLVED is done but waiting for the requester.",
            "WAITING is blocked on an approval and is not yours to action.",
          ] },
          SHOT("approver-assigned", "The assigned-ticket queue."),
        ],
      },
    ],
  },

  // ---------------------------------------------------------------- admin
  {
    slug: "overview",
    audience: "admin",
    icon: "bi-speedometer2",
    title: "Administrator overview & dashboard",
    summary: "What administrators can do, and how to read the dashboard.",
    sections: [
      {
        heading: "What an administrator can do",
        blocks: [
          { type: "bullets", items: [
            "Triage and assign every ticket (Ticket Management).",
            "Run and export reports.",
            "Manage master data: users, user groups, categories, companies, departments, lesson learned.",
            "View the activity log.",
          ] },
        ],
      },
      {
        heading: "The dashboard",
        blocks: [
          { type: "p", text: "Dashboard shows tiles for the main status buckets. Choosing a tile opens Ticket Management already filtered to that set." },
          SHOT("admin-dashboard", "The admin dashboard."),
        ],
      },
    ],
  },
  {
    slug: "ticket-management",
    audience: "admin",
    icon: "bi-kanban",
    title: "Ticket Management: triage, delete & restore",
    summary: "The admin working view for every ticket in the system.",
    sections: [
      {
        heading: "Working the queue",
        blocks: [
          { type: "p", text: "Transaction ▸ Ticket Management lists all tickets with search, status filter and sorting. Row actions let you open, assign, change status, or delete a ticket." },
          SHOT("admin-ticket-management", "Ticket Management."),
        ],
      },
      {
        heading: "Deleting and restoring",
        blocks: [
          { type: "steps", items: [
            "Choose Delete on a row and enter a reason (required).",
            "The ticket is hidden from normal lists but not erased.",
            "Turn on Show deleted to see deleted tickets and Restore them.",
          ] },
          { type: "note", variant: "warning", text: "Deleted tickets are visible to administrators only." },
        ],
      },
    ],
  },
  {
    slug: "assignment",
    audience: "admin",
    icon: "bi-people-fill",
    title: "Assigning to people and groups",
    summary: "Assign a ticket to individuals, to groups, or both.",
    sections: [
      {
        heading: "The Assign dialog",
        blocks: [
          { type: "steps", items: [
            "Open the Assign dialog from a ticket row or the ticket page.",
            "Pick one or more individual assignees and/or one or more groups.",
            "Save. The previous assignment is replaced by your selection.",
          ] },
          SHOT("admin-assign", "The assign dialog."),
          { type: "note", variant: "info", text: "Anyone assigned — directly or through a group — can see and work the ticket, and is notified. A group member sees it in their Assigned Ticket queue." },
        ],
      },
    ],
  },
  {
    slug: "master-users",
    audience: "admin",
    icon: "bi-people",
    title: "Master — Users",
    summary: "Create users, set roles and status, assign org data, import/export.",
    sections: [
      {
        heading: "Creating and editing",
        blocks: [
          { type: "steps", items: [
            "Master ▸ User ▸ New.",
            "Enter name, email, role and a password of at least 8 characters.",
            "Set Company, Department and Telephone so the user can raise tickets.",
            "Use status INACTIVE or SUSPENDED to block sign-in without deleting the account.",
          ] },
          SHOT("admin-master-users", "The user list."),
          { type: "bullets", items: [
            "ADMIN — full access.",
            "SUPERVISOR — shown as \"Approver\"; approves requests for their department(s).",
            "USER — raises and follows tickets.",
          ] },
        ],
      },
      {
        heading: "Import & export",
        blocks: [
          { type: "p", text: "Import creates or updates users from an Excel file. Export downloads the currently filtered list — including company and department — as Excel." },
        ],
      },
    ],
  },
  {
    slug: "master-user-groups",
    audience: "admin",
    icon: "bi-collection",
    title: "Master — User Groups",
    summary: "Assignment pools. A user can belong to many groups.",
    sections: [
      {
        heading: "Groups and membership",
        blocks: [
          { type: "p", text: "A user group is a pool that tickets can be assigned to. Every member of the group can then see and work those tickets." },
          { type: "steps", items: [
            "Master ▸ User Group ▸ New. Name the group and stage its members.",
            "Editing a group replaces its whole member list with what you staged.",
            "A user can be a member of several groups at once — adding them to one group never removes them from another.",
          ] },
          SHOT("admin-master-user-groups", "The user-group list with member counts."),
          { type: "note", variant: "warning", text: "A group cannot be deleted while it still has members or assigned tickets. Clear both first." },
        ],
      },
    ],
  },
  {
    slug: "master-categories",
    audience: "admin",
    icon: "bi-tags",
    title: "Master — Categories",
    summary: "Ticket categories, their owning admins, responsible groups, and approval.",
    sections: [
      {
        heading: "Setting up a category",
        blocks: [
          { type: "steps", items: [
            "Master ▸ Category ▸ New. Give it a unique name.",
            "Add Category Admins — the administrators responsible for it.",
            "Add Responsible Groups — new tickets in this category are auto-assigned to these groups.",
            "Mark it inactive to hide it from the New Ticket picker without affecting existing tickets.",
          ] },
          SHOT("admin-master-categories", "The category list."),
        ],
      },
    ],
  },
  {
    slug: "master-org",
    audience: "admin",
    icon: "bi-building",
    title: "Master — Companies & Departments",
    summary: "The org structure, and each department's approvers.",
    sections: [
      {
        heading: "Companies",
        blocks: [
          { type: "p", text: "Master ▸ Company holds each company's code, name, address and tax id. The list shows how many departments and users each has." },
          SHOT("admin-master-companies", "The company list."),
        ],
      },
      {
        heading: "Departments & approvers",
        blocks: [
          { type: "p", text: "Each department belongs to a company and has one or more approvers. Any approver of a department can decide that department's approval requests." },
          { type: "note", variant: "info", text: "A department cannot be deleted while it has users or tickets." },
        ],
      },
    ],
  },
  {
    slug: "master-lessons",
    audience: "admin",
    icon: "bi-journal-check",
    title: "Master — Lesson Learned",
    summary: "Curate the knowledge base of reusable fixes.",
    sections: [
      {
        heading: "Adding entries",
        blocks: [
          { type: "steps", items: [
            "Master ▸ Lesson Learned ▸ New.",
            "Give it a title and a description; attach images or files.",
            "Mark it inactive to retire it without deleting.",
          ] },
          SHOT("admin-master-lessons", "The lesson-learned list."),
        ],
      },
    ],
  },
  {
    slug: "reports",
    audience: "admin",
    icon: "bi-file-earmark-bar-graph",
    title: "Reports & exports",
    summary: "Main, Assignee, Category and Ticket reports, each exportable to Excel.",
    sections: [
      {
        heading: "Running a report",
        blocks: [
          { type: "steps", items: [
            "Open a report under Report in the sidebar.",
            "Set the date range and any report-specific filters, then apply.",
            "Charts and tables refresh; choose Export for the same data as Excel.",
          ] },
          SHOT("admin-reports", "A report with charts and filters."),
        ],
      },
      {
        heading: "How SLA time is measured",
        blocks: [
          { type: "p", text: "SLA time is the time from when a ticket was first assigned to when it was resolved, in days to one decimal place. Unresolved tickets show a dash." },
        ],
      },
    ],
  },
  {
    slug: "logs",
    audience: "admin",
    icon: "bi-journal-text",
    title: "Activity log",
    summary: "A record of significant actions across the system.",
    sections: [
      {
        heading: "Reading the log",
        blocks: [
          { type: "p", text: "Logs shows an audit trail of actions with the actor, the affected area and a timestamp. Use it to see who changed what and when." },
          SHOT("admin-logs", "The activity log."),
        ],
      },
    ],
  },
  {
    slug: "mcp-api",
    audience: "admin",
    icon: "bi-plug",
    title: "MCP API access",
    summary: "Let external tools work with the helpdesk as a specific user.",
    sections: [
      {
        heading: "How it works",
        blocks: [
          { type: "bullets", items: [
            "A user creates a personal access token on their Profile page.",
            "The tool calls the MCP endpoint with that token as a Bearer token.",
            "Every action runs as that user, with the same permissions they have in the app.",
            "Revoke access by deleting the token; a suspended user's token stops working immediately.",
          ] },
        ],
      },
    ],
  },
];

export function topicsForAudience(audience: ManualAudience): ManualTopic[] {
  return MANUAL_TOPICS.filter((t) => t.audience === audience);
}

export function findTopic(audience: string, slug: string): ManualTopic | undefined {
  return MANUAL_TOPICS.find((t) => t.audience === audience && t.slug === slug);
}
