import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/app/lib/db";
import { requireUser } from "@/app/lib/dal";

export const metadata: Metadata = { title: "Lesson Learned" };

export default async function LessonLearnedDetailPage({ params }: PageProps<"/lesson-learned/[id]">) {
  const session = await requireUser();

  const { id } = await params;
  const entry = await prisma.lessonLearned.findUnique({ where: { id } });

  // Non-admins can't deep-link to a hidden entry.
  if (!entry || (!entry.isActive && session.user.role !== "ADMIN")) {
    notFound();
  }

  return (
    <>
      <div className="app-content-header">
        <div className="container-fluid">
          <div className="row">
            <div className="col-sm-6">
              <h1 className="mb-0 fs-3">{entry.title}</h1>
            </div>
            <div className="col-sm-6">
              <nav aria-label="breadcrumb">
                <ol className="breadcrumb float-sm-end">
                  <li className="breadcrumb-item">
                    <Link href="/dashboard">Home</Link>
                  </li>
                  <li className="breadcrumb-item">
                    <Link href="/lesson-learned">Lesson Learned</Link>
                  </li>
                  <li className="breadcrumb-item active" aria-current="page">
                    {entry.title}
                  </li>
                </ol>
              </nav>
            </div>
          </div>
        </div>
      </div>

      <div className="app-content">
        <div className="container-fluid">
          <div className="row">
            <div className="col-12">
              <div className="card card-primary card-outline mb-4">
                <div className="card-body">
                  {/* Always Tiptap-generated by an admin through this app's own
                      editor (never raw external/pasted HTML) — safe to render. */}
                  <div dangerouslySetInnerHTML={{ __html: entry.description }} />

                  {entry.images.length > 0 && (
                    <div className="mt-4">
                      <div className="form-label text-secondary mb-1">Images</div>
                      <div className="d-flex flex-wrap gap-2">
                        {entry.images.map((url) => (
                          <a key={url} href={url} target="_blank" rel="noopener noreferrer">
                            <img
                              src={url}
                              alt=""
                              className="rounded border"
                              style={{ width: 160, height: 160, objectFit: "cover" }}
                            />
                          </a>
                        ))}
                      </div>
                    </div>
                  )}

                  <div className="mt-4">
                    <div className="form-label text-secondary mb-1">Attachments</div>
                    {entry.attachments.length === 0 ? (
                      <div className="text-secondary">No attachments.</div>
                    ) : (
                      <ul className="list-unstyled mb-0">
                        {entry.attachments.map((attachment) => (
                          <li key={attachment}>
                            <a href={attachment} target="_blank" rel="noopener noreferrer">
                              <i className="bi bi-paperclip me-1" aria-hidden="true"></i>
                              {attachment.split("/").pop()}
                            </a>
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                </div>
                <div className="card-footer">
                  <Link href="/lesson-learned" className="btn btn-secondary">
                    Back
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
